### ISSUE TITLE
License should be clarified

### ISSUE THREAD

**Issue by Calinou** [Kalabasa/furnace_time#1]
Sorry, but `Same license as in minetest/minetest_game` is too broad.

If you want to make it simple (but clear), feel free to include the MIT license for code, and [CC BY-SA](https://creativecommons.org/licenses/by-sa/3.0/) for textures.

**Comment by Kalabasa** [comment]
A major part of the code is from `minetest_game/mods/default/furnace.lua`. I modified the furnace code (the ABM part). Am I required by minetest_game's LGPL to license it the same?

But I'm using LGPL anyway.
